# Generated by Django 4.0.2 on 2022-03-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_service'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='providing',
            field=models.ManyToManyField(blank=True, null=True, related_name='providers', to='projects.Service'),
        ),
    ]
