# Generated by Django 4.0.2 on 2022-03-22 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='date_created',
            field=models.DateTimeField(default='1 April 2022'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_project_user',
            field=models.CharField(default='Sarah Smith', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_supporter',
            field=models.CharField(default='John Doe', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_name',
            field=models.CharField(default='Bob Hope', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=200),
        ),
    ]
