# Generated by Django 4.0.2 on 2022-05-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_pledge_pledge_date'),
        ('users', '0002_customuser_providing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='providing',
            field=models.ManyToManyField(related_name='providers', to='projects.Service'),
        ),
    ]
