# Generated by Django 4.0.2 on 2022-03-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_pledge_supporter_alter_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='location',
            field=models.CharField(default='Perth', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='urgent',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
