# Generated by Django 4.0.2 on 2022-03-26 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
    ]
