# Generated by Django 4.0.2 on 2022-03-28 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_remove_project_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pledge',
            name='pledge_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
